### ISSUE TITLE
kserve-controller in error with hook failed: "ingress-gateway-relation-changed"

### ISSUE THREAD

**Issue by dparv** [canonical/mlflow-operator#237]
### Bug Description

Fresh deployment on juju 3.4.3:
```
kserve-controller                                   waiting      1  kserve-controller        0.11/stable      523  10.0.27.132   no       installing agent
...
kserve-controller/0*          error     idle   10.244.0.35                 hook failed: "ingress-gateway-relation-changed"
```

### To Reproduce

juju deploy kubeflow --channel 1.8/stable

### Environment

juju 3.4.3
Azure AKS 1.28.9

### Relevant Log Output

```shell
unit-kserve-controller-0: 10:15:51 ERROR unit.kserve-controller/0.juju-log ingress-gateway:45: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 702, in <module>
    main(KServeControllerCharm)
  File "/var/lib/juju/agents/unit-kserve-controller-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-kserve-controller-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-kserve-controller-0/charm/venv/ops/framework.py", line 342, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-kserve-controller-0/charm/venv/ops/framework.py", line 839, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-kserve-controller-0/charm/venv/ops/framework.py", line 928, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 538, in _on_ingress_gateway_relation_changed
    self._on_install(event)
  File "./src/charm.py", line 495, in _on_install
    self._restart_controller_service()
  File "./src/charm.py", line 694, in _restart_controller_service
    self.controller_container.restart(self._controller_container_name)
  File "/var/lib/juju/agents/unit-kserve-controller-0/charm/venv/ops/model.py", line 2045, in restart
    self._pebble.restart_services(service_names)
  File "/var/lib/juju/agents/unit-kserve-controller-0/charm/venv/ops/pebble.py", line 1746, in restart_services
    return self._services_action('restart', services, timeout, delay)
  File "/var/lib/juju/agents/unit-kserve-controller-0/charm/venv/ops/pebble.py", line 1767, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "kserve-controller" (cannot start service: exited quickly with code 1)
----- Logs from task 0 -----
2024-06-13T10:15:51Z INFO Service "kserve-controller" has never been started.
----- Logs from task 1 -----
2024-06-13T10:15:51Z INFO Most recent service output:
    {"level":"info","ts":"2024-06-13T10:15:51Z","logger":"entrypoint","msg":"Setting up client for manager"}
    {"level":"info","ts":"2024-06-13T10:15:51Z","logger":"entrypoint","msg":"Setting up manager"}
    {"level":"info","ts":"2024-06-13T10:15:51Z","logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}
    {"level":"info","ts":"2024-06-13T10:15:51Z","logger":"entrypoint","msg":"Registering Components."}
    {"level":"info","ts":"2024-06-13T10:15:51Z","logger":"entrypoint","msg":"Setting up KServe v1alpha1 scheme"}
    {"level":"info","ts":"2024-06-13T10:15:51Z","logger":"entrypoint","msg":"Setting up KServe v1beta1 scheme"}
    {"level":"error","ts":"2024-06-13T10:15:51Z","logger":"entrypoint","msg":"unable to get deploy config.","error":"configmaps \"inferenceservice-config\" not found","stacktrace":"main.main\n\t/root/parts/controller/build/cmd/manager/main.go:141\nruntime.main\n\t/snap/go/current/src/runtime/proc.go:250"}
2024-06-13T10:15:51Z ERROR cannot start service: exited quickly with code 1
```
```


### Additional Context

_No response_

**Comment by dparv** [comment]
Wrong repo btw. should be in https://github.com/canonical/kserve-operators/
