### ISSUE TITLE
Unable to deploy alongside 1.6 kubeflow

### ISSUE THREAD

**Issue by misohu** [canonical/mlflow-operator#54]
After deploying alongside 1.6 kubeflow lite (`juju deploy kubeflow-lite --trust`) admission-webhook and mlflow-server ended up in error state. 

```
admission-webhook          res:oci-image@84a4d7d      error        1  admission-webhook        1.6/stable       50  10.152.183.216  no       hook failed: "pod-defaults-relation-changed"
argo-controller            res:oci-image@669ebd5      active       1  argo-controller          3.3/stable       99                  no       
dex-auth                                              active       1  dex-auth                 2.31/stable     129  10.152.183.220  no       
istio-ingressgateway                                  active       1  istio-gateway            1.11/stable     114  10.152.183.204  no       
istio-pilot                                           active       1  istio-pilot              1.11/stable     131  10.152.183.48   no       
jupyter-controller         res:oci-image@8f4ec33      active       1  jupyter-controller       1.6/stable      138                  no       
jupyter-ui                 res:oci-image@cde6632      active       1  jupyter-ui               1.6/stable       99  10.152.183.61   no       
kfp-api                    res:oci-image@1b44753      active       1  kfp-api                  2.0/stable       81  10.152.183.15   no       
kfp-db                     mariadb/server:10.3        active       1  charmed-osm-mariadb-k8s  latest/stable    35  10.152.183.33   no       ready
kfp-persistence            res:oci-image@31f08ad      active       1  kfp-persistence          2.0/stable       76                  no       
kfp-profile-controller     res:oci-image@d86ecff      active       1  kfp-profile-controller   2.0/stable       61  10.152.183.241  no       
kfp-schedwf                res:oci-image@51ffc60      active       1  kfp-schedwf              2.0/stable       80                  no       
kfp-ui                     res:oci-image@55148fd      active       1  kfp-ui                   2.0/stable       80  10.152.183.42   no       
kfp-viewer                 res:oci-image@7190aa3      active       1  kfp-viewer               2.0/stable       79                  no       
kfp-viz                    res:oci-image@67e8b09      active       1  kfp-viz                  2.0/stable       74  10.152.183.154  no       
kubeflow-dashboard         res:oci-image@6fe6eec      active       1  kubeflow-dashboard       1.6/stable      154  10.152.183.184  no       
kubeflow-profiles          res:profile-image@0a46ffc  active       1  kubeflow-profiles        1.6/stable       82  10.152.183.40   no       
kubeflow-roles                                        active       1  kubeflow-roles           1.6/stable       31  10.152.183.149  no       
kubeflow-volumes           res:oci-image@cc5177a      active       1  kubeflow-volumes         1.6/stable       64  10.152.183.65   no       
metacontroller-operator                               active       1  metacontroller-operator  2.0/stable       48  10.152.183.13   no       
minio                      res:oci-image@1755999      active       1  minio                    ckf-1.6/stable   99  10.152.183.228  no       
mlflow-db                  mariadb/server:10.3        active       1  charmed-osm-mariadb-k8s  stable           35  10.152.183.156  no       
mlflow-server                                         error        1  mlflow-server            stable           32                  no       hook failed: "pod-defaults-relation-joined"
oidc-gatekeeper            res:oci-image@32de216      active       1  oidc-gatekeeper          ckf-1.6/stable   76  10.152.183.23   no       
seldon-controller-manager  res:oci-image@eb811b6      active       1  seldon-core              1.14/stable      92  10.152.183.183  no       
training-operator                                     active       1  training-operator        1.5/stable       65  10.152.183.137  no       

Unit                          Workload  Agent  Address      Ports              Message
admission-webhook/0*          error     idle   10.1.189.13  4443/TCP           hook failed: "pod-defaults-relation-changed"
argo-controller/0*            active    idle   10.1.189.49                     
dex-auth/0*                   active    idle   10.1.189.10                     
istio-ingressgateway/0*       active    idle   10.1.189.11                     
istio-pilot/0*                active     idle   10.1.189.14                     
jupyter-controller/0*         active    idle   10.1.189.16                     
jupyter-ui/0*                 active    idle   10.1.189.23  5000/TCP           
kfp-api/0*                    active    idle   10.1.189.51  8888/TCP,8887/TCP  
kfp-db/0*                     active    idle   10.1.189.34  3306/TCP           ready
kfp-persistence/0*            active    idle   10.1.189.47                     
kfp-profile-controller/0*     active    idle   10.1.189.50  80/TCP             
kfp-schedwf/0*                active    idle   10.1.189.35                     
kfp-ui/0*                     active    idle   10.1.189.52  3000/TCP           
kfp-viewer/0*                 active    idle   10.1.189.37                     
kfp-viz/0*                    active    idle   10.1.189.36  8888/TCP           
kubeflow-dashboard/0*         active    idle   10.1.189.43  8082/TCP           
kubeflow-profiles/0*          active    idle   10.1.189.42  8080/TCP,8081/TCP  
kubeflow-roles/0*             active    idle   10.1.189.15                     
kubeflow-volumes/0*           active    idle   10.1.189.38  5000/TCP           
metacontroller-operator/0*    active    idle   10.1.189.19                     
minio/0*                      active    idle   10.1.189.44  9000/TCP,9001/TCP  
mlflow-server/0*              error     idle                                   hook failed: "pod-defaults-relation-joined"
oidc-gatekeeper/0*            active    idle   10.1.189.48  8080/TCP           
seldon-controller-manager/0*  active    idle   10.1.189.45  8080/TCP,4443/TCP  
training-operator/0*          active    idle   10.1.189.20
```

juju logs:
```
application-mlflow-server: 15:24:47 ERROR unit.mlflow-server/0.juju-log pod-defaults:22: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 262, in <module>
    main(Operator)
  File "/var/lib/juju/agents/unit-mlflow-server-0/charm/venv/ops/main.py", line 406, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mlflow-server-0/charm/venv/ops/main.py", line 140, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mlflow-server-0/charm/venv/ops/framework.py", line 278, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mlflow-server-0/charm/venv/ops/framework.py", line 722, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mlflow-server-0/charm/venv/ops/framework.py", line 767, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 86, in _on_pod_defaults_relation_changed
    endpoint = f"http://{os['service']}:{os['port']}"
KeyError: 'service'
application-mlflow-server: 15:24:47 ERROR juju.worker.caasoperator.uniter.mlflow-server/0.operation hook "pod-defaults-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1

application-admission-webhook: 15:27:07 ERROR unit.admission-webhook/0.juju-log pod-defaults:22: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 305, in <module>
    main(AdmissionWebhookCharm)
  File "/var/lib/juju/agents/unit-admission-webhook-0/charm/venv/ops/main.py", line 431, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-admission-webhook-0/charm/venv/ops/main.py", line 142, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-admission-webhook-0/charm/venv/ops/framework.py", line 316, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-admission-webhook-0/charm/venv/ops/framework.py", line 784, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-admission-webhook-0/charm/venv/ops/framework.py", line 857, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 158, in set_pod_spec
    pod_defaults = {
  File "./src/charm.py", line 159, in <dictcomp>
    key.name: dict(value)["pod-defaults"]
KeyError: 'pod-defaults'
application-kfp-db: 15:27:07 INFO juju.worker.caasoperator.uniter.kfp-db/0.operation ran "update-status" hook (via explicit, bespoke hook script)
application-admission-webhook: 15:27:08 ERROR juju.worker.caasoperator.uniter.admission-webhook/0.operation hook "pod-defaults-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
```

Tested locally and on AWS with the same result.

**Comment by misohu** [comment]
Latest/stable was not pointing to right revision. Should be fixed now.
